"""Render dispatch-only YAML from the canonical catalog, tasks and action pins.

This command only writes files. It does not execute, dispatch or validate builds.
"""
from __future__ import annotations

import json
from pathlib import Path
import sys

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from shared.util import ROOT, RUST, read_json, within


def render(entry, pins):
    task = entry["id"]
    request = "Rust/requests/verify-linux.json" if task == "verify-infrastructure" else ""
    # Request strings are passed as environment values; they are not embedded in shell code.
    return f'''# Generated by Rust/shared/render_workflows.py; edit task definitions and pins.
name: "Rust | {task}"
run-name: "Rust | {task} | ${{{{ inputs.request_id }}}}"
on:
  workflow_dispatch:
    inputs:
      request_path:
        description: "JSON request file under Rust/requests/"
        required: true
        type: string
        default: "{request}"
      request_ref:
        description: "Commit or ref in this repository containing the request"
        required: true
        type: string
        default: "main"
      request_id:
        description: "Unique ID matching the request JSON"
        required: true
        type: string
        default: "{'verify-linux' if task == 'verify-infrastructure' else ''}"
permissions:
  contents: read
concurrency:
  group: "rust-{task}-${{{{ inputs.request_id }}}}-${{{{ github.run_id }}}}"
  cancel-in-progress: false
jobs:
  prepare:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    outputs:
      matrix: ${{{{ steps.prepare.outputs.matrix }}}}
      request_id: ${{{{ steps.prepare.outputs.request_id }}}}
      request_commit: ${{{{ steps.prepare.outputs.request_commit }}}}
    steps:
      - name: Checkout infrastructure
        uses: actions/checkout@{pins['checkout']}
        with:
          persist-credentials: false
      - name: Install orchestration Python
        uses: actions/setup-python@{pins['setup_python']}
        with:
          python-version: "{pins['python']}"
      - name: Resolve request and target matrix
        id: prepare
        shell: bash
        env:
          REQUEST_PATH: ${{{{ inputs.request_path }}}}
          REQUEST_REF: ${{{{ inputs.request_ref }}}}
          REQUEST_ID: ${{{{ inputs.request_id }}}}
          GH_TOKEN: ${{{{ github.token }}}}
        run: python Rust/shared/run.py prepare --task {task}
  execute:
    needs: prepare
    strategy:
      fail-fast: false
      matrix: ${{{{ fromJSON(needs.prepare.outputs.matrix) }}}}
    runs-on: ${{{{ matrix.runner }}}}
    timeout-minutes: 120
    steps:
      - name: Checkout exact infrastructure commit
        uses: actions/checkout@{pins['checkout']}
        with:
          ref: ${{{{ github.sha }}}}
          persist-credentials: false
      - name: Install orchestration Python
        uses: actions/setup-python@{pins['setup_python']}
        with:
          python-version: "{pins['python']}"
      - name: Cache Cargo dependency downloads
        uses: actions/cache@{pins['cache']}
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: "rust-downloads-${{{{ runner.os }}}}-${{{{ runner.arch }}}}-${{{{ github.sha }}}}-${{{{ matrix.target }}}}-${{{{ needs.prepare.outputs.request_commit }}}}"
      - name: Execute requested task on the runner
        shell: bash
        env:
          REQUEST_PATH: ${{{{ inputs.request_path }}}}
          REQUEST_REF: ${{{{ needs.prepare.outputs.request_commit }}}}
          REQUEST_ID: ${{{{ needs.prepare.outputs.request_id }}}}
          BUILD_TARGET: ${{{{ matrix.target }}}}
          GH_TOKEN: ${{{{ github.token }}}}
          SOURCE_TOKEN: ${{{{ secrets.RUST_SOURCE_TOKEN }}}}
        run: python Rust/tasks/{task}/scripts/execute.py execute
      - name: Upload report and available products
        if: always()
        uses: actions/upload-artifact@{pins['upload_artifact']}
        with:
          name: "rust-{task}-${{{{ needs.prepare.outputs.request_id }}}}-${{{{ matrix.target }}}}-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}"
          path: Rust/.runs/**/report/**
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 14
'''


def main():
    pins = read_json(RUST / "toolchains/pins.json")
    for entry in read_json(RUST / "catalog.json")["tasks"]:
        destination = within(ROOT, entry["workflow"])
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(render(entry, pins), encoding="utf-8")


if __name__ == "__main__":
    main()
